server:
  port: 8081
#SWAGGER CONFIG http://localhost:8080/documentation/swagger-ui/
documentation:
  host: localhost:8081
springfox:
  documentation:
    swagger-ui:
      base-url: /documentation
#FILE SERVICE CONFIG
files:
  upload-path: /home/beatinho/Downloads

#DATABASE CONFIG
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

#SECURITY CONFIG

security:
  token:
    validity:
      seconds: 3600
  signing-key: QNqfec5qxwwIqCLVJX7qY55WSxMBrbMiO


---
spring:
  config:
    activate:
      on-profile: development

  datasource:
    url: postgres://ykdazgwogmohwu:cfcea1dc19f9050eac4a5a1f834e0abd0fda4845f2c2f03c9f0a9c3e70440aad@ec2-3-218-47-9.compute-1.amazonaws.com:5432/d6kbm1r3sti6eb
    username: ykdazgwogmohwu
    password: cfcea1dc19f9050eac4a5a1f834e0abd0fda4845f2c2f03c9f0a9c3e70440aad
