INSERT INTO localizations (city, voivodeship) VALUES ('Gdańsk', 'POMORSKIE')
INSERT INTO localizations (city, voivodeship) VALUES ('Szczecin', 'ZACHODNIO_POMORSKIE')
INSERT INTO localizations (city, voivodeship) VALUES ('Olsztyn', 'WARMINSKO_MAZURSKIE')
INSERT INTO localizations (city, voivodeship) VALUES ('Białystok', 'PODLASKIE')
INSERT INTO localizations (city, voivodeship) VALUES ('Toruń', 'KUJAWSKO_POMORSKIE')
INSERT INTO localizations (city, voivodeship) VALUES ('Poznań', 'WIELKOPOLSKIE')
INSERT INTO localizations (city, voivodeship) VALUES ('Zielona Góra', 'LUBUSKIE')
INSERT INTO localizations (city, voivodeship) VALUES ('Wrocław', 'DOLNOSLASKIE')
INSERT INTO localizations (city, voivodeship) VALUES ('Łódź', 'LODZKIE')
INSERT INTO localizations (city, voivodeship) VALUES ('Kielce', 'SWIETOKRZYSKIE')
INSERT INTO localizations (city, voivodeship) VALUES ('Lublin', 'LUBELSKIE')
INSERT INTO localizations (city, voivodeship) VALUES ('Opole', 'OPOLSKIE')
INSERT INTO localizations (city, voivodeship) VALUES ('Katowice', 'SLASKIE')
INSERT INTO localizations (city, voivodeship) VALUES ('Kraków', 'MALOPOLSKIE')
INSERT INTO localizations (city, voivodeship) VALUES ('Rzeszów', 'PODKARPACKIE')